first update
EarthSciML/tutorials pull request #1
Opened 2021-09-09 06:33 UTC by minwoos2

Created heatequation, plotted, and created an animation

2021-09-10 16:04 UTC, minwoos2 commented
I have reviewed and hereby sign the CLA

2021-09-10 16:59 UTC, ctessum requested changes
Looking good!

2021-09-10 16:59 UTC, ctessum commented on heatequation.jl
> +u_exact = (x,t) -> exp.(-t) * cos.(x)
I think we're not using this any more. If so, it can be deleted.

2021-09-10 16:59 UTC, ctessum commented on heatequation.jl
> +#xmax = 50.0
You can delete these variables we're not using any more

2021-09-10 16:59 UTC, ctessum commented on heatequation.jl
> +emisrate = 10;
Do you need to define emisrate above where it is used? It seems like how it is now might cause an error if you run the file from beginning to end.

2021-09-10 16:59 UTC, ctessum commented on heatequation.jl
> +analytic_sol_func(t,x,y) = exp(x+y)*cos(x+y+4t)
You can delete this and related things below if they're not being used any more

2021-09-10 16:59 UTC, ctessum commented on heatequation.jl
> +# Ploting
Ploting -> Plotting

2021-09-23 15:45 UTC, ctessum commented on heatequation.jl
> +using OrdinaryDiffEq, ModelingToolkit, DiffEqOperators, DomainSets
Since you've added the file with the different name, you can also remove this file.

2021-12-06 16:29 UTC, merged